version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  node-backend:
    build: .
    container_name: node-backend
    ports:
      - 3000:3000
    environment:
      PG_PASSWORD: root
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
